title: Xiaoyu Zhu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Enthusiast | Investment Specialist | Curious Human Being 
  <br><br>
  Shanghai &#9992; Pittsburgh &#9992; Boston &#9992; Shanghai 
  <br><br>
  Contact: <a href="mailto:xyzhu76@outlook.com">Email Me</a>
  <br><br>
  <a href="https://www.linkedin.com/in/xiaoyu-zhu-46732418/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-Y3Z3VQ3X78 # your Google Analytics tracking ID here
